version: '2'
services:
    onlineshop-app:
        image: onlineshop
        environment:
            - _JAVA_OPTIONS=-Xmx256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://onlineshop-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=onlineshop
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
    onlineshop-mongodb:
        extends:
            file: mongodb.yml
            service: onlineshop-mongodb
